### ISSUE TITLE
setup-gcloud does not work in example

### ISSUE THREAD

**Issue by trevoro** [GoogleCloudPlatform/github-actions#10]
it appears as though the `setup-gcloud` action in the example does not work. The workflow example cited in this repository and on the marketplace uses ubuntu-latest as the image, but its missing python-openssl from the base image as well as a setting . To make it work, this repository either needs to include it itself (probably not considering how sparse this is) _or_ you need to do the following

```
...
env:
    CLOUDSDK_PYTHON_SITEPACKAGES: 1

...

    # steps
 
    - name: install python-openssl
       run: sudo apt-get install -y python-openssl -o=Dpkg::Use-Pty=0

```
