### ISSUE TITLE
setup-gcloud - Automatically set project from service account if not specified

### ISSUE THREAD

**Issue by Mark-McCracken** [GoogleCloudPlatform/github-actions#114]
### TL;DR
If the user sets a service_account, I think this demonstrates clear intent to use it with a project. If they don't set the project explicitly, we leave it unset. Since all service accounts must be associated with a project, would be convenient, and almost expected, to set the project as the project that the service account belongs to.

### Design
If project_id is not set, and service account is set, set the project to the service account's project.

Yaml would have one less line required.

**Comment by sethvargo** [comment]
Hi @Mark-McCracken - thank you for opening an issue and PR. I'll leave my thoughts here, but they apply to the PR too. In short, I don't think this is a good idea. It may make sense for a few use cases, but many customers use cross-project service accounts, and this level of magic could be confusing and difficult to debug.

Yes, service accounts must be associated with a project, but they doesn't mean they are associated with a project _you_ control or a project upon which they have access to resources. I can create a service account that lives in project A (e.g. `mycorp-security`) and then grant it no permissions on project A. At the same time, I can grant it Owner on project B (e.g. `mcorp-app1`). This model is becoming more common, especially among larger companies with many projects.

**Comment by Mark-McCracken** [comment]
Hi Seth! Thanks for taking the time to look :)

Yeah, I totally understand that often times users will work across multiple projects, or collaborate with teams where service accounts reach across project boundaries.
But surely in this case, the user MUST be explicit about what project they want? They're absolutely required to put in that project ID they want to work with, because they need to be aware that the service account and resources live in different projects.

But I'd argue that in most cases, users are using a service account in the same project it belongs to.
What should happen in this case? The default at the minute sets no project, forcing the user to later provide the project when they want to use it, so they're basically forced to set it either on every command, or here.
I think when a user provides a service account and they haven't explicitly mentioned using a different project, automatically setting the project for them to the most common case, is more useful than not setting it at all, leaving their gcloud config in a state where it can't be used without extra flags.

I think as long as it's clearly mentioned in the docs, and the default is sensible, then I wouldn't call it magic, magic to me is something where lots of un-obvious steps that make lots of assumptions are performed in a way that's hidden completely from the user, that makes it look a lot simpler than it is. I think in this case, it's a simple enough step and default to be intuitive to users.

But I'll understand if you don't agree. I'm not gonna die on this hill, as it literally just saves on line lol.
Cheers

**Comment by sethvargo** [comment]
> But I'd argue that in most cases, users are using a service account in the same project it belongs to.

This is the assumption I challenge. I work with a _lot_ of customers and can assuredly tell you this is false 😄.

> What should happen in this case?

People should explicitly declare _which_

> so they're basically forced to set it either on every command

That's certainly one way to look at it. Another way to frame this is that each command must explicitly declare upon _which_ project it will interact. 

> automatically setting the project for them to the most common case

As mentioned above, this is not true.

> is more useful than not setting it at all, leaving their gcloud config in a state where it can't be used without extra flags.

We already provide a convenient way to configure the project, explicitly via the `project_id` field. You don't need to specify per-command flags if you don't want to.

> I think as long as it's clearly mentioned in the docs, and the default is sensible, then I wouldn't call it magic, magic to me is something where lots of un-obvious steps that make lots of assumptions are performed in a way that's hidden completely from the user, that makes it look a lot simpler than it is.

Consider the following, assuming this change is implemented:

At t0, my admin gives me a service account and says "here, go use this". I set it up, works great, as the project is inferred from the service account. A few months go by and my company changes their security policies. They give me a new service account in a _different_ project. It has all the same permissions on the original project, but the service account resides in a parent project. I install the service account, expecting everything to work just great... best case scenario, I get permission denied errors. Worst case scenario, I create damages in the wrong project.

**Comment by sethvargo** [comment]
Hi there - I'm gonna close this out. Please feel free to comment if you'd like more discussion. Thanks!

**Comment by treeder** [comment]
Could there be a flag for this? So by default, it won't do this, but if you set the flag, say: 

```
with:
  use_project_from_key: true
  # or  
  project_id: from_key
```

For anyone else that finds that and wants to reduce a bunch of duplicate steps based on just the project id, you can use the following to only dupe the setup-gcloud step:

```yaml
      - if: github.ref == 'refs/heads/staging'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.STAGING_G_KEY }}
          project_id: ${{ secrets.STAGING_G_PROJECT_ID }}
      - if: github.ref == 'refs/heads/master'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.G_KEY }}
          project_id: ${{ secrets.G_PROJECT_ID }}
      # now we put the project_id in output for use later
      - id: gcstep
        run: echo "::set-output name=project_id::$(gcloud config get-value project)"
      # then use it throughout
      - name: Build
        run: |
          docker build -t gcr.io/${{steps.gcstep.outputs.project_id}}/service_name:$GITHUB_SHA .
```
