### ISSUE TITLE
Getting no credentials provided

### ISSUE THREAD

**Issue by jainkunal** [GoogleCloudPlatform/github-actions#126]
### Question

Trying to setup github action for my private repo and here is the step for setting up gcloud
```
- name: Setup Gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '275.0.0'
        service_account_key: ${{ secrets.GCLOUD_KEY }}
        export_default_credentials: true
```
I always get the following output
![image](https://user-images.githubusercontent.com/435610/84602091-f8074a00-ae52-11ea-922e-854617705f55.png)

Seems like it never recognizes `service_account_key` is provided. Any insights or help is appreciated.
