### ISSUE TITLE
gsutil Support

### ISSUE THREAD

**Issue by spiray** [GoogleCloudPlatform/github-actions#13]
@craigdbarber Is there any plan of having a gsutil action included in this repo? There doesn't seem to be anything now. [This PR](https://github.com/actions/gcloud/pull/6) implements it but it was never merged and it looks like that repo wont exist after 12/31/2019. Thanks!

**Comment by craigdbarber** [comment]
@spiray thanks for the feedback. gsutil is included in the bundle that's downloaded with the gcloud sdk. Have you tried invoking gsutil after running the current setup-gcloud action?

**Comment by ferreiratiago** [comment]
@spiray After setting up your gcloud action you can call gsutil as you would do it on your terminal.

Here's an example:
```
- name: Authenticate on GCS
  uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  with:
    version: '270.0.0'
    service_account_email: ${{ secrets.GKE_EMAIL }}
    service_account_key: ${{ secrets.GKE_KEY }}

- name: Build
  run: yarn build

- name: Deploy
  run: gsutil cp -r dist/* gs://some-storage/
```
