### ISSUE TITLE
app-engine deploy does not work with: credentials

### ISSUE THREAD

**Issue by maxheld83** [GoogleCloudPlatform/github-actions#136]
### TL;DR
The `with: credentials` way to auth `GoogleCloudPlatform/github-actions/appengine-deploy@master` does not appear to work.

**Expected behavior**

I expected the action to deploy.

**Observed behavior**

A yaml parsing error:

```
Unexpected input(s) 'credentials', valid inputs are ['project_id', 'deliverables', 'image_url', 'version', 'promote']
```

### Reproduction

**Action YAML**

```yaml
 - name: Deploy to GCP
    if: github.event_name != 'pull_request'
    uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
    with:
       project_id: ${{ secrets.GCP_PROJECT_ID }}
       credentials: ${{ secrets.GCP_SA_KEY }}
       version: ${{ github.ref }}
       promote: ${{ github.ref == 'refs/heads/master' }}
```

**Repository**

https://github.com/subugoe/hoad/commit/6b828043da4958486cbad6598af1983f7479e9ae

**Additional information**

Nothing weird.

Above YAML that I used should be the same as in https://github.com/GoogleCloudPlatform/github-actions/blob/master/appengine-deploy/README.md

> ### Via Credentials
>
> You can provide [Google Cloud Service Account JSON][sa] directly to the action
> by specifying the `credentials` input. First, create a [GitHub
> Secret][gh-secret] that contains the JSON content, then import it into the
> action:
> 
> ```yaml
> - id: Deploy
>   uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
>   with:
>     credentials: ${{ secrets.GCP_SA_KEY }}
> ```
>
