### ISSUE TITLE
cannot find latest release

### ISSUE THREAD

**Issue by dakom** [GoogleCloudPlatform/github-actions#14]
I have:

**build.yml**
```
- uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
   with:
     version: '272.0.0'
     service_account_key: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_JSON_KEY }}
```

When I look at the logs, I see:

```
(node:7088) UnhandledPromiseRejectionWarning: Error: Failed to find release, os: linux arch: x64 version: 272.0.0
```

Interestingly some of my commands do seem to run okay, though maybe it's the previously cached version?

Cloud run, which was made GA in this version, does _not_ run:

**build.yml**
```
- name: Deploy
   run: gcloud run deploy --image gcr.io/"$GOOGLE_CLOUD_PROJECT"/"$CONTAINER_IMAGE":"$GITHUB_SHA" --platform managed
```

**Result:**
```
ERROR: (gcloud) Invalid choice: 'run'.
This command is available in one or more alternate release tracks.  Try:
  gcloud alpha run
  gcloud beta run
```
