### ISSUE TITLE
deploy-cloudrun action does not inherit authentication credentials from the setup-gcloud action

### ISSUE THREAD

**Issue by lmakarov** [GoogleCloudPlatform/github-actions#157]
### TL;DR

`deploy-cloudrun` action does not inherit authentication credentials from the `setup-gcloud` action.

**Expected behavior**

`deplot-cloudrun` is able to inherit the authentication credentials exported by the `setup-gcloud` action as described in ["Used with setup-gcloud"](https://github.com/GoogleCloudPlatform/github-actions/tree/master/deploy-cloudrun#used-with-setup-gcloud).

**Observed behavior**

Getting the "No method for authentication. Set credentials in this action or export credentials from the setup-gcloud action" error.

```
Run GoogleCloudPlatform/github-actions/deploy-cloudrun@master
  with:
    image: gcr.io/***/b2b-api-backend:4bd4c55db34154ca5b4d6e2d5e9d1575e6181edb
    service: b2b-api-backend
    region: us-central1
  env:
    GCP_PROJECT: ***
    GCP_REGION: us-central1
    REGISTRY_HOSTNAME: gcr.io
    IMAGE: b2b-api-backend
    GITHUB_SHA: 4bd4c55db34154ca5b4d6e2d5e9d1575e6181edb
    DEPLOYMENT_NAME: b2b-api-backend
    CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
    GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/b2b-api/b2b-api/49b66433-b1ba-470c-81ea-dce4370f5918
    IMAGE_URL: gcr.io/***/b2b-api-backend:4bd4c55db34154ca5b4d6e2d5e9d1575e6181edb
##[error]Error: No method for authentication. Set credentials in this action or export credentials from the setup-gcloud action
##[error]No method for authentication. Set credentials in this action or export credentials from the setup-gcloud action
```

The error goes away if using the [credentials method](https://github.com/GoogleCloudPlatform/github-actions/tree/master/deploy-cloudrun#via-credentials) and passing `credentials: ${{ secrets.GCP_SA_KEY }}`.

### Reproduction

**Action YAML**

```yaml
name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: us-central1
  REGISTRY_HOSTNAME: gcr.io
  IMAGE: b2b-api-backend
  GITHUB_SHA: ${{ github.sha }}
  DEPLOYMENT_NAME: b2b-api-backend

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Google Cloud CLI (gcloud)
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '303.0.0'
          project_id: ${{ env.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build & Publish
        run: |
          gcloud builds submit \
          --quiet \
          --tag "${REGISTRY_HOSTNAME}/${GCP_PROJECT}/${IMAGE}:${GITHUB_SHA}"

      - name: Deploy
        id: deploy
        env:
          IMAGE_URL: ${{ env.REGISTRY_HOSTNAME }}/${{ env.GCP_PROJECT }}/${{ env.IMAGE }}:${{ env.GITHUB_SHA }}
        uses: GoogleCloudPlatform/github-actions/deploy-cloudrun@master
        with:
          #credentials: ${{ secrets.GCP_SA_KEY }}
          image: ${{ env.IMAGE_URL }}
          service: ${{ env.DEPLOYMENT_NAME }}

      - name: Test API Endpoint
        run: curl -sSI "${{ steps.deploy.outputs.url }}"
```

**Additional information**

Getting identical results with `setup-gcloud` `version: '290.0.1'` and `version: '303.0.0'`.
