### ISSUE TITLE
Add a "build and deploy to Cloud Run" example workflow

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/github-actions#17]
GitHub Actions are an ideal way to automatically build and deploy to [Cloud Run](https://cloud.run).

I suggest we add an [example workflow](https://github.com/GoogleCloudPlatform/github-actions/tree/master/example-workflows)

There already are a lot of such third party tutorials:
  - [Deploying projects to Cloud Run using GitHub Actions](https://misfra.me/2019/09/deploying-projects-to-cloud-run-using-github-actions/)
  - [Publish your Cloud Run App with GitHub Actions](https://medium.com/better-programming/publish-your-cloud-run-app-with-github-actions-6c18ff5c5ee4)
  -  [Automate Cloud Run deployment in a minute (with GitHub actions)](https://medium.com/@ujwaldhakal/automate-cloud-run-deployment-in-a-minute-cb85e7db9f82)
  - [Github Action for Google Cloud Run](https://github.com/marketplace/actions/cloud-run)

**Comment by craigdbarber** [comment]
Thanks @steren for the feedback. We'll incorporate this information into our roadmap planning process. In the meantime, feel free to submit a PR for any new example workflows you'd like to see.

**Comment by pollosp** [comment]
```
name: Deploy the application to Google Cloud Run
on:
  push:
    branches:
      - 'master'

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
      
    # Build the Docker image
    - name: Build
      run: |        
        docker build . --tag eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        docker push eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}
        
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud components install beta && gcloud beta run deploy ${{ secrets.GCLOUD_APP_NAME }} --quiet --image eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }} --project ${{ secrets.GCLOUD_PROJECT }} --region europe-west1 --platform managed
```
Just in case someone need it before having it official.
