### ISSUE TITLE
Synchronize folder as the bucket root

### ISSUE THREAD

**Issue by FFY00** [GoogleCloudPlatform/github-actions#175]
### TL;DR

Uploading a folder like this, will upload to `bucket-name/folder`. I want to synchronize the bucket root, `/path/to/folder` would be the root of my bucket. `/path/to/folder/a` would be `bucket-name/a`, not `bucket-name/folder/a`.
```yaml
steps:
  - id: upload-files
    uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
    with:
      path: /path/to/folder
      destination: bucket-name
```

### Design

**Action YAML**

I propose introducing a `root` input.
```yaml
steps:
  - id: upload-files
    uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
    with:
      path: /path/to/folder
      destination: bucket-name
      root: true
```
