### ISSUE TITLE
Connection to Cloud SQL is deleted with every new revision

### ISSUE THREAD

**Issue by BooDy** [GoogleCloudPlatform/github-actions#179]
### TL;DR
Connection to Cloud SQL from Cloud Run is deleted with every deployment

**Expected behavior**
if a connection exists in a Cloud Run deployment it shouldn't be deleted when a new revision is deployed.

**Observed behavior**
once the action is triggered a new revision is deployed correctly, however the connection to a Cloud SQL instance created before no longer exists

### Reproduction

**Action YAML**

```yaml
      - name: Deploy cloud run
        uses: GoogleCloudPlatform/github-actions/deploy-cloudrun@master
        with:
          image: gcr.io/cosmic-tenure-290110/core:latest
          service: <service name>
          credentials: ${{ secrets.GCLOUD_DEPLOY_RUN }}
          env_vars: 

```
