### ISSUE TITLE
Application default credentials not set

### ISSUE THREAD

**Issue by theomessin** [GoogleCloudPlatform/github-actions#18]
I tried using this step right before using Pulumi to orchestrate some infrastructure on GCP. However, Pulumi's whining about ADC: 

```
 +  pulumi:pulumi:Stack infrastructure-develop create 
    gcp:storage:Bucket my-bucket-eO4o4P1qpwmyq4U7Mk5Jq27FTj3t08IZ  error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
 +  pulumi:pulumi:Stack infrastructure-develop create 
    gcp:storage:Bucket my-bucket-eO4o4P1qpwmyq4U7Mk5Jq27FTj3t08IZ  1 error
 
Diagnostics:
  gcp:storage:Bucket (my-bucket-eO4o4P1qpwmyq4U7Mk5Jq27FTj3t08IZ):
    error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

I assumed that using this action as a setup step before using Pulumi would work, but apparently that's not the case. Any ideas?

**Comment by craigdbarber** [comment]
Hi @theomessin apologies for any confusion. When the gcloud CLI is installed it does not automatically setup ADC, as this would be problematic from a security perspective. You can however incorporate this into your workflow using these commands:

`gcloud iam service-accounts keys create [FILE_NAME].json --iam-account [NAME]@[PROJECT_ID].iam.gserviceaccount.com`
`export GOOGLE_APPLICATION_CREDENTIALS="[FILE_NAME].json"`

**Comment by brachipa** [comment]
@craigdbarber  I tried this, but get from my application, file not found

**Comment by brachipa** [comment]
opened up a PR: https://github.com/GoogleCloudPlatform/github-actions/pull/30

**Comment by harscoet** [comment]
> Hi @theomessin apologies for any confusion. When the gcloud CLI is installed it does not automatically setup ADC, as this would be problematic from a security perspective. You can however incorporate this into your workflow using these commands:
> 
> `gcloud iam service-accounts keys create [FILE_NAME].json --iam-account [NAME]@[PROJECT_ID].iam.gserviceaccount.com`
> `export GOOGLE_APPLICATION_CREDENTIALS="[FILE_NAME].json"`

This command will create a new key every time action is runned, it can be a bit messy

I use the following in my workflow

```yaml
env:
    GOOGLE_APPLICATION_CREDENTIALS: key.json
steps:
- uses: actions/checkout@v2
- uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  with:
      version: '270.0.0'
      service_account_key: ${{ secrets.GCP_SA_KEY }}
- run: echo -n ${{ secrets.GCP_SA_KEY }} | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS
```
