### ISSUE TITLE
GitHub Actions: Deprecating set-env and add-path commands 

### ISSUE THREAD

**Issue by viggin543** [GoogleCloudPlatform/github-actions#188]
### TL;DR

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

currently when using the `setup-gcloud` action 
I get the following warnings:
```
 Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Expected behavior**
the action should be updated to the new GitHub API

**Observed behavior**
deprecation warning ( if not updated to the new GitHub actions API the action will stop working )

### Reproduction

any workflow using setup-gcloud action will cause this warning.

```yaml
    - name: Setup gcloud cli
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCLOUD_PROJECT_KEY }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        export_default_credentials: true
```
