### ISSUE TITLE
PyOpenSSL is not available

### ISSUE THREAD

**Issue by abdonrd** [GoogleCloudPlatform/github-actions#19]
Hello!

I was trying to deploy an application to Google App Engine.
I get the workflow from the documentation example:

```yaml
deploy:
  name: Deploy to Google App Engine

  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v1

    - name: Setup Google Cloud Platform
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '273.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - run: gcloud info
```

But I get this error:

> Run GoogleCloudPlatform/github-actions/setup-gcloud@master
> gcloud auth activate-service-account *** --key-file=/tmp/tmp-17045ATDT0qazBcZQ
> /bin/tar xz -C /home/runner/work/_temp/692985c1-383b-42c2-b29a-37c2cde1bad8 -f /home/runner/work/_temp/9e89d332-df66-4ffe-9c86-fb577f3c514d
> WARNING: .p12 service account keys are not recomended unless it is necessary for backwards compatability. Please switch to a newer .json service account key for this account.
> ERROR: (gcloud.auth.activate-service-account) PyOpenSSL is not available. If you have already installed PyOpenSSL, you will need to enable site packages by setting the environment variable CLOUDSDK_PYTHON_SITEPACKAGES to 1. If that does not work, see https://developers.google.com/cloud/sdk/crypto for details or consider using .json private key instead.
> ##[error]The process 'gcloud' failed with exit code 1
> ##[error]Node run failed with exit code 1

**Comment by craigdbarber** [comment]
Hi @abdonrd thanks for reporting this issue. Some further information is required to help debug the issue:
Is the service account key you're trying to use a .p12 key?

**Comment by abdonrd** [comment]
I create the key selecting the JSON option:

<img width="516" alt="Screenshot 2019-12-18 at 19 24 50" src="https://user-images.githubusercontent.com/1007051/71112581-1ce47280-21cc-11ea-8fcf-d4544d234409.png">

And then I use the fields:
* `private_key` for the `GCP_SA_EMAIL`
* `client_email` for the `GCP_SA_KEY`

You mean that?

**Comment by craigdbarber** [comment]
@abdonrd thanks for following up. That is indeed the key I mean. A follow up question, was the key Base64 encoded prior to be stored as a secret? See: https://github.com/GoogleCloudPlatform/github-actions/tree/master/setup-gcloud#inputs

**Comment by abdonrd** [comment]
Ouch! I forget to encode the key to base64! Thanks, it works now!

**Comment by bibimorlet** [comment]
Hello everyone!

It doesn't work for me. I have the same error:

```bin/bash
WARNING: .p12 service account keys are not recomended unless it is necessary for backwards compatability. Please switch to a newer .json service account key for this account.
ERROR: (gcloud.auth.activate-service-account) PyOpenSSL is not available. If you have already installed PyOpenSSL, you will need to enable site packages by setting the environment variable CLOUDSDK_PYTHON_SITEPACKAGES to 1. If that does not work, see https://developers.google.com/cloud/sdk/crypto for details or consider using .json private key instead.
##[error]The process '/opt/hostedtoolcache/gcloud/270.0.0/x64/bin/gcloud' failed with exit code 1
```


My workflow is:

```yml
jobs:
  setup-build-publish:
    if: github.event.pull_request.merged == true
    name: name
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_KEY }}
```
I created a service account with its JSON key.
I created the secrets in github repository.
In GCP_EMAIL I have the "client_email" field of the JSON key file.
In GCP_KEY I have the "private_key" field of the JSON key file.

For example, the private_key is like:
```json
"-----BEGIN PRIVATE KEY-----\nMYPRIVATEKEY\n-----END PRIVATE KEY-----"
```
Does anyone have a solution for me?
Thanks
