### ISSUE TITLE
Google app engine deploy action stopped working overnight

### ISSUE THREAD

**Issue by mishacajic** [GoogleCloudPlatform/github-actions#191]
### TL;DR

Without any changes on our end, this action stopped working overnight. It fails to deploy to app engine due to a service account error and no change we've tried have fixed it.

**Expected behavior**

App should deploy to app engine normally as it did before.

**Observed behavior**

Action fails at the deploy step with the following error:
```
ERROR: (gcloud.app.deploy) PERMISSION_DENIED: You do not have permission to act as '[project id redacted]@appspot.gserviceaccount.com'
27
- '@type': type.googleapis.com/google.rpc.ResourceInfo
28
  description: You do not have permission to act as this service account.
29
  resourceName: [redacted]@appspot.gserviceaccount.com
30
  resourceType: serviceAccount
```

It seems like now the action attempts to use the default gcloud service account credentials rather than the service account I set up for it, even though I have `export_default_credentials: true`. It doesn't recognise the newly exported credentials.

### Reproduction

**Action YAML**

```yaml
name: Backend staging CI

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CI: ""

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Set up authentication to google cloud via the service account
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install node dependencies
        run: npm ci
      - name: Deploy to google cloud
        run: |
          gcloud config set project [project id redacted]
          gcloud app deploy api-staging.yaml --quiet

```

Any help would be appreciated. Thanks!
