### ISSUE TITLE
[deploy-cloudrun] is not creating new revisions, just replacing the old ones

### ISSUE THREAD

**Issue by MoSattler** [GoogleCloudPlatform/github-actions#192]
### TL;DR
Whenever I deploy an image via deploy-cloudrun, it wont create a new revision, and instead just replaces the old one.

**Expected behavior**
Creating a new revision on every deploy

**Observed behavior**
It just replaces the old revision

### Reproduction

**Action YAML**

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations: {}
  labels:
    cloud.googleapis.com/location: europe-west1
  name: my-service
  namespace: "123456789"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1000"
    spec:
      containerConcurrency: 80
      containers:
        - image: eu.gcr.io/my-service-291508/server:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi

      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
```

**Additional information**
I am using version 0.1.3
