### ISSUE TITLE
gcloud functions deploy

### ISSUE THREAD

**Issue by xylo04** [GoogleCloudPlatform/github-actions#208]
### TL;DR
A new action which will allow deploying code to Google Cloud Functions.

### Design

**Action YAML**

```yaml
name: Deploy to Google Cloud Functions
description: Deploy the repository to Google Cloud Functions
inputs:
  function-name:
    description: The name of the cloud function
    required: true
  entry-point:
    description: The method that should be invoked
    required: true
  runtime:
    description: Which Cloud Functions runtime should be used
    required: true
  trigger-http:
    description: Whether the function should be triggered by HTTP calls
    required: false
  trigger-bucket:
    description: Which GCS buckets should trigger this function
    required: false
  allow-unauthenticated:
    description: Whether to allow unauthenticated users to trigger the function
    required: false

# similar to other GCP actions
  env_vars:
    description: |-
      List of key-value pairs to set as environment variables in the format:
      KEY1=VALUE1,KEY2=VALUE2. All existing environment variables will be
      removed first.
    required: false
  project_id:
    description: The GCP project ID. Overrides project ID set by credentials.
    required: false
  credentials:
    description: |-
      Service account key to use for authentication. This should be the JSON
      formatted private key which can be exported from the Cloud Console. The
      value can be raw or base64-encoded. Required if not using a the
      setup-gcloud action with exported credentials.
    required: false

outputs:
  version:
    description: The version of the newly deployed function
```

**Resources**

- [gcloud functions deploy](https://cloud.google.com/sdk/gcloud/reference/functions/deploy)

**Additional information**
