### ISSUE TITLE
Generate dist for deploy-cloud-functions

### ISSUE THREAD

**Issue by xylo04** [GoogleCloudPlatform/github-actions#216]
### TL;DR
Generate `dist` for `deploy-cloud-functions`.

**Expected behavior**
As of PR #160 getting merged yesterday, I should be able to use the action.

**Observed behavior**
From https://github.com/xylo04/simple-cloud-func/runs/1300898779 (not sure if you can see the logs)

```
Run GoogleCloudPlatform/github-actions/deploy-cloud-functions@master
Error: File not found: '/home/runner/work/_actions/GoogleCloudPlatform/github-actions/master/deploy-cloud-functions/dist/index.js'
```

### Reproduction

**Action YAML**
https://github.com/xylo04/simple-cloud-func/blob/main/.github/workflows/main.yml

```yaml
name: Continuous Delivery

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Deploy the code to Cloud Functions
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: GCP Auth
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Cloud Functions Deploy
        uses: GoogleCloudPlatform/github-actions/deploy-cloud-functions@master
        with:
          name: Hello
          entry_point: Hello
          runtime: go113
```

**Repository**
https://github.com/xylo04/simple-cloud-func/

**Additional information**
N/A
