### ISSUE TITLE
Ability to specify latest gcloud version

### ISSUE THREAD

**Issue by brettski** [GoogleCloudPlatform/github-actions#31]
While setting up the action you specify the version of gcloud to use, E.g. `174.0.0.1`. Have the ability to specify latest version. 

### Example
```yml
steps:
- uses: actions/checkout@v1
- uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  with:
      version: 'latest'
      service_account_email: ${{ secrets.GCP_SA_EMAIL }}
      service_account_key: ${{ secrets.GCP_SA_KEY }}
- run: gcloud info
```

If changing major versions may not be desirable without prior testing, perhaps a semver-type formatting to run at any patched or minor versions of the major version specified.

example: `version: '^274.0.0'`
