### ISSUE TITLE
Feature request: actions for working with cloud storage

### ISSUE THREAD

**Issue by pingvinen** [GoogleCloudPlatform/github-actions#32]
In my projects, I often have to build and publish documentation as static websites. I typically host these files with Cloud Storage, so having an easy to use action that takes a folder in my repository and uploads it to a given bucket.

Perhaps a simplified workflow could be something like:

```yaml
name: Master workflow

on:
  push:
    branches:
      - master

jobs:
  build-and-publish-docs:
    name: Build and publish documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build documentation
        run: |
          do whatever to build the documentation
      - uses: ____/publish-to-gcs@v666
        with:
          source-folder: ./generated/docs/of/doom
          bucket-name: my-amazeballs-bucket
          object-key-prefix: /the-docs/1.0.1/
          clear-existing-files-first: true
```
