### ISSUE TITLE
[Proposal] Deploy to App Engine

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/github-actions#61]
I will makes use of the already needed setup-gcloud (wrap the gcloud command) in order not to recreate the features of gcloud:
* Uploading files to GCS
* Authentication
* Yaml parsing
* Creating and managing the GAE application, services and versions (deployment) 
* Flags
* Java specifics (deploying appengine-web.xml, jars)

## Prioritized functionality (gcloud flags, see inputs below)
* Deployables (app.yaml, cron, index …)
* Promote
* Version name
* Image url (for flex)

## Deployable types: (Argument for not recreating gcloud)
* Single: app.yaml
* Java8: appengine-web.xml
* Java11: my_jar.jar
* Multiple apps: ~/my_app/app.yaml ~/my_app/another_service.yaml
* Multiple configs: app.yaml, index.yaml

## Authentication methods:
* Exported credentials from setup-gcloud action
* Github secret with service account JSON
* Hosted runner

## IAM Roles implications (based on comparison)
* App Engine Deployer (minimal config) - deploys but can not promote
* App Engine Admin (maximum config) - All the power
* App Engine Service Admin - Can not deploy but can migrate/start/stop traffic
*Note:* Storage Admin role and Cloud Build Editor role are needed to use gcloud commands
*Note:* An owner will be needed to create the App Engine application

example action.yaml
```YAML
name: 'Deploy to Google App Engine'
description: 'Deploy to Google App Engine'
author: 'GoogleCloudPlatform'

inputs:
  project_id:
    description: 'The GCP project ID'
    require: false
  deliverables:
    description: |-
      The yaml files for the services or configurations you want to deploy.
      If not given, defaults to app.yaml in the current directory. If that is
      not found, attempts to automatically generate necessary configuration
      files (such as app.yaml) in the current directory.'
    required: false
  image-url:
    description: |-
      Deploy with a specific Docker image. Docker url must be from one of the
      valid gcr hostnames.
    required: false
  version:
    description: |-
      The version of the app that will be created or replaced by this
      deployment. If you do not specify a version, one will be generated for
      you.'
    required: false
  promote:
    description: 'Promote the deployed version to receive all traffic.'
    default: true
    required: false

outputs:
  url:
    description: 'URL of your App Engine Application'

runs:
  using: node12
  main: dist/index.js
```

Other notes:
* There is no GAE Admin Node.js library. Having a library or using a REST call would need additional work to copy the files over the GCS + additional steps.
