### ISSUE TITLE
Setup GCloud Using Python 3.x within container fails to find path.

### ISSUE THREAD

**Issue by Andrewangeta** [GoogleCloudPlatform/github-actions#73]
Here is my workflow file for using it.
Notice this is running in a swift container from [here](https://github.com/vapor/docker/blob/master/swift/5.2-bionic/Dockerfile)

```yaml
jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-latest

    container: 
      image: vapor/swift:5.2-bionic

    steps:
    - name: 'Checking out repo'
      uses: actions/checkout@v2
      
    - name: 'Installing Python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: 'Downloading and Setting up gcloud'
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: ${{secrets.EMAIL}}
        service_account_key: ${{secrets.KEY}}
```

I'm getting the following error 

<img width="1331" alt="Screen Shot 2020-03-16 at 9 37 35 AM" src="https://user-images.githubusercontent.com/12012815/76763577-c60a1d00-6769-11ea-9161-25ad47c7e8f1.png">

Any pointers or commands I can try maybe setting the path or something else?

**Comment by sethvargo** [comment]
The default for gcloud is still Python 2. You can force it to use Python 3 by setting the `GCLOUDSDK_PYTHON` environment variable: 

```
export CLOUDSDK_PYTHON=python3
```

Does that help? See `gcloud topic startup` for more information.

**Comment by Andrewangeta** [comment]
@sethvargo Cool I'll try it out and let you know. I'd just add a run command correct?
```yaml
- name: 'Downloading and Setting up gcloud'
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: ${{secrets.EMAIL}}
        service_account_key: ${{secrets.KEY}}
      run: export CLOUDSDK_PYTHON=python3
```

**Comment by sethvargo** [comment]
It should be:

```yaml
- name: install-gcloud
  uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  with: 
    # ...
  env:
    CLOUDSDK_PYTHON: python3
```

**Comment by Andrewangeta** [comment]
@sethvargo Hmmmm still no dice. 
`python3: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory `.

**Comment by Andrewangeta** [comment]
Could this be the fact that it's running in the swift container? I wouldn't think so since I can still install gcloud to it as well as python etc. Any reason why not installing python be default in the action wasn't done?

**Comment by Andrewangeta** [comment]
oh maybe it's `GCLOUDSDK_PYTHON` vs `CLOUDSDK_PYTHON`

**Comment by Andrewangeta** [comment]
That didn't help either surprisingly.

**Comment by sethvargo** [comment]
I'm not entirely sure. We should support this use case though. @craigdbarber any ideas?

**Comment by Andrewangeta** [comment]
I usually used this one but wanted to use the official one but might switch back to this one for now 
https://github.com/actions-hub/gcloud

**Comment by sethvargo** [comment]
I spent some time digging today. I **can** reproduce this using `vapor/swift:5.2-bionic` as the base container image, but I **cannot** reproduce this using the default container image. 

After installing some additional packages into the container, I am able to get Python to find openssl and correctly initialize the SDK.

```
$ apt-get -yqq update && apt-get install -yqq libpython*-dev openssl libssl-dev libreadline-dev libncursesw5-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
```

Furthermore, I was able to reproduce this issue with a very simple action:

```yaml
    name: setup-gcloud latest
    runs-on: ubuntu-latest

    container:
      image: vapor/swift:5.2-bionic

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - name: info
        run: 'python -c "import httplib; print dir(httplib)"'
```

I do not believe it is the responsibility of this action to install or manage those packages. I would also argue that it's not the responsibility of the setup-python action to have those packages installed, since most actions assume the default runtime. 

If you want to use a custom base image, I'd recommend starting from the default actions base image and pulling your specific requirements into that instead: https://github.com/actions/virtual-environments/tree/master/images/linux.

> I usually used this one but wanted to use the official one but might switch back to this one for now https://github.com/actions-hub/gcloud

So, the reason this works is because the actions-hub/gcloud command distributes the entire gcloud runtime in an isolated container. This action installs gcloud into your environment and makes it available to other steps on the toolpath.

**Comment by Andrewangeta** [comment]
@SethVargo
Super late follow up but I just got it to work a minute ago. So setting up python with the setup-python action is supposed to install it so other steps can use it. Turns out that specifying a specific version wasn’t the best way to go about it. Instead specifying `pypy3` it could resolve the libraries etc. 
```yaml
container: 
      image: vapor/swift:5.2-bionic

    steps:
    - name: 'Checking out repo'
      uses: actions/checkout@v2
        
    - name: 'Installing Python'
      uses: actions/setup-python@v1
      with:
        python-version: 'pypy3'
        architecture: 'x64'
      
    - run: export CLOUDSDK_PYTHON=python3
```
