### ISSUE TITLE
export_default_credentials: true isn't setting $GOOGLE_APPLICATION_CREDENTIALS for later steps

### ISSUE THREAD

**Issue by brachi-wernick** [GoogleCloudPlatform/github-actions#80]
### TL;DR
I set `export_default_credentials: true`, and in later steps test failed due to missing credentials.

**Expected behavior**
`$GOOGLE_APPLICATION_CREDENTIALS` should be set with the credentials for all later steps.

### Reproduction

**Action YAML**

```yaml
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
       version: '270.0.0'
       service_account_email: ${{ secrets.GCP_SA_STG_EMAIL }}
       service_account_key: ${{ secrets.GCP_SA_STG_KEY }}
       export_default_credentials: true
    - name: set gcp cradentilas
      run:  gcloud info
    - name: echo gcp cradentilas
      run:  echo this is  ${GOOGLE_APPLICATION_CREDENTIALS}  
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install --file pom.xml
```

**Additional information**
I submitted in the past some [PR](https://github.com/GoogleCloudPlatform/github-actions/pull/30) that fixed it, when I run same action with that PR branch it works.
