### ISSUE TITLE
Support .env files

### ISSUE THREAD

**Issue by ndeitch** [GoogleCloudPlatform/github-actions#94]
### TL;DR
Create `.env` file with secrets fetched

### Design
```yaml
steps:
- id: secrets
  uses: GoogleCloudPlatform/github-actions/get-secretmanager-secrets@master
  with:
    secrets: my-project/user-service
    dotenv: true
    overwriteFile: true
```

`overwrite` flag tells if we should remove existing `.env` file or not.

The following would happen:

- Fetch secrets for `my-projects/user-service`
- Remove `.env` file if `overwrite === true`
- Create `.env` with secrets obtained

**Comment by sethvargo** [comment]
Hi @ndeitch - thank you for opening an issue. Can you tell us a bit more about your use case?

It's very common in the GitHub Actions ecosystem to limit each action to one specific operation. It feels like fetching secrets **and** saving secrets to a file violates this promise. 

Since secrets are stored as outputs for future build steps, could you use another action step to create the `.env` file?

```yaml
steps:
- id: secrets
  uses: GoogleCloudPlatform/github-actions/get-secretmanager-secrets@master
  with:
    secrets: |-
      token:my-project/my-secret
- id: createEnv
  run: |-
    cat > .env <<EOF
    ${steps.secrets.outputs.token}
    EOF
```

I'm also a bit unclear on the desired behavior, since `.env` files typically have a `KEY=VALUE` format, but only the key is provided.

**Comment by ndeitch** [comment]
Hi @sethvargo thanks for fast reply,

We store our `.env` file as a secret with the following format: 
```
key1=value1
key2=value2
```
then we fetch this content and as it is we overwrite the local `.env`.

Today we've the following steps:

```yml
- name: Setup gcloud
  uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  with:
    project_id: some-project
    service_account_key: ${{ secrets.GCP_SA_KEY }}
    export_default_credentials: true

- name: Fetch .env
  run: rm -f .env && gcloud secrets versions access latest --secret="some-project" >> .env
```

So, what I'm suggesting is to create support for this use case, which downloads latest version of some key and creates a brand new `.env` with secret's content.
